# Generated by Django 3.1.2 on 2020-10-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201002_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesource',
            name='source_id',
            field=models.CharField(max_length=50),
        ),
    ]
